---
apiVersion: v1
kind: ReplicationController
metadata:
  name: front-end
  namespace: sock-shop
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: front-end
    spec:
      containers:
      - name: front-end
        image: weaveworksdemos/front-end:0.2.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8079
        securityContext:
#          runAsNonRoot: true
#          runAsUser: 10001
          capabilities:
            drop:
              - all
#          readOnlyRootFilesystem: true
